export { default as Hero } from "./Hero";
export { default as Split } from "./Split";
export { default as Stats } from "./Stats";
export { default as TextBlock } from "./TextBlock";
export { default as RichText } from "./RichText";
export { default as Video } from "./Video";
export { default as TeamGrid } from "./TeamGrid";
export { default as ImageBlock } from "./ImageBlock";
export { default as Gallery } from "./Gallery";
export { default as Quote } from "./Quote";
export { default as Accordion } from "./Accordion";
export { default as Contact } from "./Contact";
export { default as ImpactStats } from "./ImpactStats";
export { default as CampaignGrid } from "./CampaignGrid";
export { default as InitiativesGrid } from "./InitiativesGrid";
export { default as MissionsGrid } from "./MissionsGrid";
export { default as EventsGrid } from "./EventsGrid";
export { default as Partners } from "./Partners";

// Aliases für Mappings (Falls du missionsSection/eventsSection nutzt)
export { default as MissionsSection } from "./MissionsGrid";
export { default as EventsSection } from "./EventsGrid";
