import {
  Hero,
  TextBlock,
  RichText,
  ImageBlock,
  Video,
  Stats,
  ImpactStats,
  Accordion,
  Split,
  Gallery,
  Quote,
  TeamGrid,
  Partners,
  CampaignGrid,
  InitiativesGrid,
  MissionsGrid,
  EventsGrid,
  Contact,
} from "@/components/site/sections";

export const SECTION_COMPONENTS: Record<string, any> = {
  heroSection: Hero,
  textBlock: TextBlock,
  richTextSection: RichText,
  imageBlock: ImageBlock,
  videoSection: Video,
  statsSection: Stats,
  impactStatsSection: ImpactStats,
  splitSection: Split,
  gallerySection: Gallery,
  quoteSection: Quote,
  accordionSection: Accordion,
  teamSection: TeamGrid,
  partnersSection: Partners,
  eventsGrid: EventsGrid,
  contactSection: Contact,

  // GRID SECTIONS
  missionsGrid: MissionsGrid,
  initiativesGrid: InitiativesGrid,
  campaignGrid: CampaignGrid,
};
